### ISSUE TITLE
The axis argument to unique is not supported for dtype object on cn.calculate_quantiles

### ISSUE THREAD

**Issue by sinnamone** [TarikExner/CytoNormPy#3]
Hi,

I have test on my data biex-transformed before import. 

cn = cnp.CytoNorm()

#t = cnp.AsinhTransformer()
fs = cnp.FlowSOM(n_clusters = 10)

#cn.add_transformer(t)
cn.add_clusterer(fs)

cn.run_anndata_setup(adata2,
                     layer= 'compensated',
    reference_column= 'reference',
    reference_value= 'ref',
    batch_column= 'batch',
    sample_identifier_column= 'file_name',
    channels= 'markers',
    key_added= 'cyto_normalized')

cn.run_clustering(cluster_cv_threshold = 2)

cn.calculate_quantiles()
cn.calculate_splines(goal = "batch_median")
cn.normalize_data()

when I go to  cn.calculate_quantiles() gave me this error "The axis argument to unique is not supported for dtype object". 

There is a way to solve or pass "quantile_array"? In case of quantile_array how should be structured?

**Comment by TarikExner** [comment]
Hey,

This sounds like your "batch" column entry in adata2.obs is probably of dtype "object"?

This is clearly an oversight on my part. I will add a solution as soon as I can. In the meantime, could you convert the batch-values to integers?

Best,
Tarik

**Comment by sinnamone** [comment]
Yes,

it was an object, now I have converted:

adata2.obs['batch'] = adata2.obs['batch'].astype(int)

but going ahed the same cell gave me this:

The shapes of `y` and `dydx` must be identical.

here the full error:

ValueError                                Traceback (most recent call last)
Cell In[39], line 2
      1 cn.calculate_quantiles()
----> 2 cn.calculate_splines(goal = "batch_mean")
      3 cn.normalize_data()

File ~/opt/miniconda3/envs/Cytophenograph7/lib/python3.11/site-packages/cytonormpy/_cytonorm/_cytonorm.py:571, in CytoNorm.calculate_splines(self, limits, goal)
    563                 g = goal_distrib.get_quantiles(channel_idx = ch,
    564                                                quantile_idx = None,
    565                                                cluster_idx = c,
    566                                                batch_idx = None)
    567                 spl = Spline(batch = batch,
    568                              cluster = cluster,
    569                              channel = channel,
    570                              limits = limits)
--> 571                 spl.fit(q, g)
    572                 splines.add_spline(spl)
    574 self.splinefuncs = splines

File ~/opt/miniconda3/envs/Cytophenograph7/lib/python3.11/site-packages/cytonormpy/_normalization/_spline_calc.py:137, in Spline.fit(self, current_distribution, goal_distribution)
    128 current_distribution, goal_distribution = regularize_values(
    129     current_distribution,
    130     goal_distribution
    131 )
    133 m = self._select_interpolants(
    134     current_distribution,
    135     goal_distribution
    136 )
--> 137 self.fit_func: PPoly = self.spline_calc_function(
    138     current_distribution,
    139     goal_distribution,
    140     dydx = m,
    141     extrapolate = True if self._extrapolate is not False else False
    142 )
    143 if self._extrapolate == "linear":
    144     self._extrapolate_linear()

File ~/opt/miniconda3/envs/Cytophenograph7/lib/python3.11/site-packages/scipy/interpolate/_cubic.py:141, in CubicHermiteSpline.__init__(self, x, y, dydx, axis, extrapolate)
    138 if extrapolate is None:
    139     extrapolate = True
--> 141 x, dx, y, axis, dydx = prepare_input(x, y, axis, dydx)
    143 dxr = dx.reshape([dx.shape[0]] + [1] * (y.ndim - 1))
    144 slope = np.diff(y, axis=0) / dxr

File ~/opt/miniconda3/envs/Cytophenograph7/lib/python3.11/site-packages/scipy/interpolate/_cubic.py:36, in prepare_input(x, y, axis, dydx)
     34 dydx = np.asarray(dydx)
     35 if y.shape != dydx.shape:
---> 36     raise ValueError("The shapes of `y` and `dydx` must be identical.")
     37 if np.issubdtype(dydx.dtype, np.complexfloating):
     38     dtype = complex

ValueError: The shapes of `y` and `dydx` must be identical.

**Comment by TarikExner** [comment]
If you uncomment the transformer addition, does it work? I vaguely remember a similar situation, but since we almost never use untransformed data, this case might have slipped.


Best,
Tarik

**Comment by sinnamone** [comment]
Yes, the input data is transformed so I have put the comment in order to avoid double transformation.

**Comment by TarikExner** [comment]
I'll get to it as fast as I can!

Thanks for reporting!

**Comment by TarikExner** [comment]
Hey, just a quick update: I found the bug. It is due to all-zero quantiles, at least in my datasets. If there is only one unique value, the Fritsch Carlson algorithm fails with the current implementation. I will get a fix ready :)

In the meantime: For me it helped tremendously to reduce the number of clusters in the FlowSOM call (n_clusters=15).

Best,
Tarik

**Comment by TarikExner** [comment]
Sorry for the misclick for closing.

Do you mind trying it out again?

I now implemented the fixes for string batch labels as well as the bug that caused you the shape mismatch when calculating the spline functions.

Best,
Tarik

**Comment by sinnamone** [comment]
Hi,
no problem I could test in 30 minute. 

Thanks

**Comment by sinnamone** [comment]
the problem seems solved. 

I have just a naive question, when you perform this part of the script 


filename = "Gates_PTLG034_Unstim_Control_2_dup.fcs"
metadata = pd.DataFrame(
    data = [[filename, "other", 3]],
    columns = ["file_name", "reference", "batch"]
)
new_adata = _fcs_to_anndata(input_directory, filename, 7, metadata)

dataset = ad.concat([dataset, new_adata], axis = 0, join = "outer")
dataset

You add a new sample to the already trained model in order to perform correction if I have understood well.  

For the training do you suggest to mix control and treated sample (for example in my design I have 6 Healthy donor+ 6 Treatment) ? 

After this step I have to add all other treated sample ?

I hope that I was clear. 


Simone

**Comment by TarikExner** [comment]
Perfect, good to hear!

Yes, we implemented the addition of new samples so that one would not necessarily have to train the SOM or other clustering algorithm again. This is meant to be in compliance with the R package and is, imo, a relatively specific use case where you dont have all samples collected by the time of the first use of CytoNorm.

In your case: It doesnt really matter when you add your other samples but I would recommend assembling them beforehand. The first step is always to collect the "reference" samples and do all calculations based on them. Since you define the reference samples in your metadata (or adata.obs), this is already done. After that, all other present samples are fed to the algorithm, clustered and then normalized. If you already have all samples readily at hand, you just mark them as "other" in the metadata and you are good to go.

For your question about the kind of samples used for training its hard to answer since I dont know exactly how many batches there were and which samples belonged to which batch. Ideally, you would have one sample per batch (and per condition maybe) that acts as a "standard" and is used to estimate the technical variability of the marker expressions. All other samples would be "non-reference" samples.

I hope that was somewhat helpful :)

Feel free to reopen if there are any more problems!
